"""empty message

Revision ID: b13ea046c630
Revises: c7f2a62b4bc0
Create Date: 2018-06-23 08:46:14.489335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b13ea046c630'
down_revision = 'c7f2a62b4bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_login_username'), 'user_login', ['username'], unique=True)
    op.create_table('role_Permission_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('per_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['per_id'], ['permission.per_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('role_permission_relation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permission_relation',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('per_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['per_id'], ['permission.per_id'], name='role_permission_relation_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='role_permission_relation_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('role_Permission_relation')
    op.drop_index(op.f('ix_user_login_username'), table_name='user_login')
    op.drop_table('user_login')
    # ### end Alembic commands ###
