"""empty message

Revision ID: c7f2a62b4bc0
Revises: d714785912d7
Create Date: 2018-06-22 10:27:22.094181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f2a62b4bc0'
down_revision = 'd714785912d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('per_id', sa.Integer(), nullable=False),
    sa.Column('per_name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('per_id')
    )
    op.create_index(op.f('ix_permission_per_name'), 'permission', ['per_name'], unique=True)
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('role_Permission_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('per_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['per_id'], ['permission.per_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['user_shop.sid'], ),
    sa.PrimaryKeyConstraint('did')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail')
    op.drop_table('role_Permission_relation')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_per_name'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
